# Numpy Practice

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
import array

# what is an array?
my_array = array.array('i', [1, 2, 3, 4, 5])
print(my_array) # prints: array('i', [1, 2, 3, 4, 5])


array('i', [1, 2, 3, 4, 5])


In [6]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [7]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [8]:
# converting 1D into 2D.
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [9]:
a.shape

(6,)

In [10]:
a2.shape

(1, 6)

In [11]:
a3 = a[:, np.newaxis]
print(a3)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
a3.shape

(6, 1)

In [15]:
a_3d = a2[:, np.newaxis]
print(a_3d)
print(a_3d.shape)

[[[0 1 2 3 4 5]]]
(1, 1, 6)


# Why we have 1D, 2D or 3D arrays and where we need them in Data Sciene?

In [21]:
# Creating Arrays with Numpy
a = np.array([1, 2, 3, 4, 5])
b = np.array([(4, 5, 6, 5, 4), (4, 5, 6, 7, 8)])
print(a, b)
print(a.shape)
print(b.shape)

[1 2 3 4 5] [[4 5 6 5 4]
 [4 5 6 7 8]]
(5,)
(2, 5)


# Intialize Arrays


In [26]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
ones = np.ones((4,4))
ones, ones.shape

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 (4, 4))

In [33]:
full = np.full((2,5), 9)
full

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [34]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
i.dtype # shows data type of elements in an array.

dtype('float64')

In [37]:
type(i) # type of array

numpy.ndarray

In [41]:
# array attributes.
a.shape, i.shape, len(a)

((5,), (5, 5), 5)

In [42]:
i.ndim # gives the dimension of array

2

In [43]:
i.size # gives total no. of elements in an array.

25

In [44]:
len(i) # gives length of array

5

# Basik operations.

In [45]:
g = a -b
g

array([[-3, -3, -3, -1,  1],
       [-3, -3, -3, -3, -3]])

In [46]:
h = a + b
h

array([[ 5,  7,  9,  9,  9],
       [ 5,  7,  9, 11, 13]])

In [47]:
h1 = np.add(a,b)
h1

array([[ 5,  7,  9,  9,  9],
       [ 5,  7,  9, 11, 13]])

In [48]:
x = a * b
x

array([[ 4, 10, 18, 20, 20],
       [ 4, 10, 18, 28, 40]])

In [49]:
j = a/b
j

array([[0.25      , 0.4       , 0.5       , 0.8       , 1.25      ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ]])

In [50]:
a

array([1, 2, 3, 4, 5])

In [51]:
a7 = a**2
a7

array([ 1,  4,  9, 16, 25])

In [58]:
# what is purpose of a^2? a^2 = bitwise XOR operation.
a8 = a^2
a8

array([3, 0, 1, 6, 7], dtype=int32)